Attempting to make github CI fail on collection failure; reverting files which I wasn't supposed to track. No collected tests is exit code 5 in pytest, but github only considers 1 as a failure.

diff --git a/.github/workflows/continuous_integration.yml b/.github/workflows/continuous_integration.yml
--- a/.github/workflows/continuous_integration.yml
+++ b/.github/workflows/continuous_integration.yml
@@ -47,6 +47,15 @@ jobs:
     - name: Test with pytest
       run: |
         pytest |& tee coverage.txt
+        env:
+          PYTEST_EXIT_CODE: $?
+
+    - name: Check pytest exit code
+      run: |
+        if [ "$PYTEST_EXIT_CODE" -ne 0 ]; then
+          echo "pytest failed with exit code $PYTEST_EXIT_CODE"
+          exit 1
+        fi
 
     - name: Run update-badges script
       run: |
